#!/bin/sh
set -u
. /etc/storage/ourfw/runtime/ourfw-common.sh || exit 1
load_global || exit 1
TAG="${1:-default}"
safe_id "$TAG" || exit 2
[ "${OURFW_ENABLED:-1}" = "1" ] || { echo "OURFW_DISABLED=1"; exit 0; }

txn_lock_acquire || { echo "another transaction is active" >&2; exit 3; }
trap 'txn_lock_release >/dev/null 2>&1 || true' EXIT HUP INT TERM

# A pending marker with a dead/missing guard means the previous caller crashed.
if [ -f "$STATE/pending" ]; then
    if pid_alive "$STATE/rollback-guard.pid"; then echo "another transaction is pending" >&2; exit 3; fi
    log "configuration: stale pending detected; restoring last-good"
    OURFW_LOCK_HELD=1 "$OURFW/runtime/ourfw-rollback.sh" now >/dev/null 2>&1 || { echo "stale rollback failed" >&2; exit 4; }
fi
if [ -f "$STATE/update-pending" ]; then
    if pid_alive "$STATE/update-guard.pid"; then echo "component transaction is pending" >&2; exit 3; fi
    log "configuration: stale component pending detected; restoring module"
    OURFW_LOCK_HELD=1 "$OURFW/runtime/ourfw-update.sh" rollback >/dev/null 2>&1 || { echo "stale component rollback failed" >&2; exit 4; }
fi

[ -f "$STATE/last-good.tar" ] || ( cd "$OURFW" && tar -cf "$STATE/last-good.tar" config profiles rules 2>/dev/null ) || exit 4
printf '%s\n' "$TAG" > "$STATE/pending" || exit 4

# Arm rollback BEFORE touching networking. If this shell dies mid-apply the
# independent guard still restores last-good.
(
    sleep "$ROLLBACK_TIMEOUT"
    n=0
    while [ -f "$STATE/pending" ] && [ "$n" -lt 15 ]; do
        "$OURFW/runtime/ourfw-rollback.sh" now >/dev/null 2>&1 && exit 0
        n=$((n+1)); sleep 2
    done
) >/dev/null 2>&1 &
echo $! > "$STATE/rollback-guard.pid"

# Optional candidate installation is performed only AFTER pending+guard exist.
# WebUI editors therefore never expose a crash window where a new config is
# persistent in /etc/storage but no rollback timer is armed.
install_candidate() {
    if [ -n "${OURFW_CANDIDATE_SRC:-}" ] || [ -n "${OURFW_CANDIDATE_REL:-}" ]; then
        src="${OURFW_CANDIDATE_SRC:-}"; rel="${OURFW_CANDIDATE_REL:-}"
        [ -f "$src" ] || { log "candidate: source missing"; return 1; }
        case "$src" in /tmp/ourfw-*|/tmp/ourfw/*) ;; *) log "candidate: unsafe source"; return 1;; esac
        case "$rel" in
          config/*.conf|profiles/vpn.conf|profiles/nfqws.strategy|rules/*.list|dnsmasq-ourfw.conf) ;;
          *) log "candidate: unsafe destination $rel"; return 1;;
        esac
        dst="$OURFW/$rel"; mkdir -p "$(dirname "$dst")" || return 1
        tmp="$dst.candidate.$$"; cp "$src" "$tmp" || return 1
        case "$rel" in profiles/vpn.conf) chmod 600 "$tmp" 2>/dev/null || true;; *) chmod 644 "$tmp" 2>/dev/null || true;; esac
        mv "$tmp" "$dst" || return 1
        log "candidate installed: $rel"
    fi

    if [ -n "${OURFW_CANDIDATE_PATCH:-}" ]; then
        arc="$OURFW_CANDIDATE_PATCH"
        case "$arc" in /tmp/ourfw-*|/tmp/ourfw/*) ;; *) log "candidate patch: unsafe source"; return 1;; esac
        [ -f "$arc" ] || return 1
        stage="$STATE/patch-tree.$$"; rm -rf "$stage"; mkdir -p "$stage" || return 1
        bzip2 -dc "$arc" | tar -xf - -C "$stage" || { rm -rf "$stage"; return 1; }
        # Patch archives are generated by OURFW itself and contain only the
        # mutable config/profile/rule paths validated by ourfw-transfer.sh.
        for top in config profiles rules; do
            [ -d "$stage/$top" ] || continue
            find "$stage/$top" -type f | while IFS= read -r src; do
                rel=${src#"$stage"/}; dst="$OURFW/$rel"
                mkdir -p "$(dirname "$dst")" || exit 1
                tmp="$dst.candidate.$$"; cp "$src" "$tmp" || exit 1
                case "$rel" in profiles/vpn.conf) chmod 600 "$tmp" 2>/dev/null || true;; *) chmod 644 "$tmp" 2>/dev/null || true;; esac
                mv "$tmp" "$dst" || exit 1
            done || { rm -rf "$stage"; return 1; }
        done
        rm -rf "$stage"
        log "candidate patch installed"
    fi

    if [ -n "${OURFW_CANDIDATE_BACKUP:-}" ]; then
        arc="$OURFW_CANDIDATE_BACKUP"
        case "$arc" in /tmp/ourfw-*|/tmp/ourfw/*) ;; *) log "candidate backup: unsafe source"; return 1;; esac
        [ -f "$arc" ] || return 1
        stage="$STATE/restore-tree.$$"; rm -rf "$stage"; mkdir -p "$stage" || return 1
        bzip2 -dc "$arc" | tar -xf - -C "$stage" || { rm -rf "$stage"; return 1; }
        for d in config profiles rules; do [ -d "$stage/$d" ] || { rm -rf "$stage"; log "backup restore: missing $d"; return 1; }; done
        rm -rf "$OURFW/config" "$OURFW/profiles" "$OURFW/rules"
        cp -a "$stage/config" "$stage/profiles" "$stage/rules" "$OURFW/" || { rm -rf "$stage"; return 1; }
        find "$OURFW" -type f -name '*.sh' -exec chmod 755 {} \; 2>/dev/null || true
        [ -f "$OURFW/profiles/vpn.conf" ] && chmod 600 "$OURFW/profiles/vpn.conf" 2>/dev/null || true
        rm -rf "$stage"
        log "backup candidate installed"
    fi
}

apply_modules() {
    for m in vpn smart-routing dns nfqws watchdog diagnostics; do
        hook="$OURFW/modules/$m/apply.sh"; [ -x "$hook" ] || continue
        log "apply module: $m"; "$hook" || return 1
    done
}
if ! install_candidate; then
    OURFW_LOCK_HELD=1 "$OURFW/runtime/ourfw-rollback.sh" now >/dev/null 2>&1 || true
    exit 5
fi

if ! apply_modules; then
    OURFW_LOCK_HELD=1 "$OURFW/runtime/ourfw-rollback.sh" now >/dev/null 2>&1 || true
    exit 5
fi

echo "PENDING_CONFIRM=1"
echo "ROLLBACK_IN=$ROLLBACK_TIMEOUT"
